// protobuf有两个版本，默认版本是proto2，如果需要3则在第一行使用这行代码表明版本。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.19.1
// source: enum_allow_alias.proto

// 可选的，主要用来防止不同的消息类型有命名冲突

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnumAllowAlias_Status int32

const (
	EnumAllowAlias_UNKNOWN EnumAllowAlias_Status = 0
	EnumAllowAlias_STARTED EnumAllowAlias_Status = 1
	EnumAllowAlias_RUNNING EnumAllowAlias_Status = 1
)

// Enum value maps for EnumAllowAlias_Status.
var (
	EnumAllowAlias_Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "STARTED",
		// Duplicate value: 1: "RUNNING",
	}
	EnumAllowAlias_Status_value = map[string]int32{
		"UNKNOWN": 0,
		"STARTED": 1,
		"RUNNING": 1,
	}
)

func (x EnumAllowAlias_Status) Enum() *EnumAllowAlias_Status {
	p := new(EnumAllowAlias_Status)
	*p = x
	return p
}

func (x EnumAllowAlias_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnumAllowAlias_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_allow_alias_proto_enumTypes[0].Descriptor()
}

func (EnumAllowAlias_Status) Type() protoreflect.EnumType {
	return &file_enum_allow_alias_proto_enumTypes[0]
}

func (x EnumAllowAlias_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnumAllowAlias_Status.Descriptor instead.
func (EnumAllowAlias_Status) EnumDescriptor() ([]byte, []int) {
	return file_enum_allow_alias_proto_rawDescGZIP(), []int{0, 0}
}

type EnumAllowAlias struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EnumAllowAlias) Reset() {
	*x = EnumAllowAlias{}
	if protoimpl.UnsafeEnabled {
		mi := &file_enum_allow_alias_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnumAllowAlias) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumAllowAlias) ProtoMessage() {}

func (x *EnumAllowAlias) ProtoReflect() protoreflect.Message {
	mi := &file_enum_allow_alias_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumAllowAlias.ProtoReflect.Descriptor instead.
func (*EnumAllowAlias) Descriptor() ([]byte, []int) {
	return file_enum_allow_alias_proto_rawDescGZIP(), []int{0}
}

var File_enum_allow_alias_proto protoreflect.FileDescriptor

var file_enum_allow_alias_proto_rawDesc = []byte{
	0x0a, 0x16, 0x65, 0x6e, 0x75, 0x6d, 0x5f, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x5f, 0x61, 0x6c, 0x69,
	0x61, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0x45,
	0x0a, 0x0e, 0x45, 0x6e, 0x75, 0x6d, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x41, 0x6c, 0x69, 0x61, 0x73,
	0x22, 0x33, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e,
	0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x54, 0x41, 0x52, 0x54,
	0x45, 0x44, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x55, 0x4e, 0x4e, 0x49, 0x4e, 0x47, 0x10,
	0x01, 0x1a, 0x02, 0x10, 0x01, 0x42, 0x08, 0x5a, 0x06, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_enum_allow_alias_proto_rawDescOnce sync.Once
	file_enum_allow_alias_proto_rawDescData = file_enum_allow_alias_proto_rawDesc
)

func file_enum_allow_alias_proto_rawDescGZIP() []byte {
	file_enum_allow_alias_proto_rawDescOnce.Do(func() {
		file_enum_allow_alias_proto_rawDescData = protoimpl.X.CompressGZIP(file_enum_allow_alias_proto_rawDescData)
	})
	return file_enum_allow_alias_proto_rawDescData
}

var file_enum_allow_alias_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_enum_allow_alias_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_enum_allow_alias_proto_goTypes = []interface{}{
	(EnumAllowAlias_Status)(0), // 0: main.EnumAllowAlias.Status
	(*EnumAllowAlias)(nil),     // 1: main.EnumAllowAlias
}
var file_enum_allow_alias_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_enum_allow_alias_proto_init() }
func file_enum_allow_alias_proto_init() {
	if File_enum_allow_alias_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_enum_allow_alias_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnumAllowAlias); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_enum_allow_alias_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_enum_allow_alias_proto_goTypes,
		DependencyIndexes: file_enum_allow_alias_proto_depIdxs,
		EnumInfos:         file_enum_allow_alias_proto_enumTypes,
		MessageInfos:      file_enum_allow_alias_proto_msgTypes,
	}.Build()
	File_enum_allow_alias_proto = out.File
	file_enum_allow_alias_proto_rawDesc = nil
	file_enum_allow_alias_proto_goTypes = nil
	file_enum_allow_alias_proto_depIdxs = nil
}
